## Primary configuration, do not delete.
title: TinyDocs
favicon: favicon.png
theme: Light.css # Themes in `styles/themes/`

## Modules (optional)
modules:
 subtitle:
 logo:
 content:
 metadata:
 search: